[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.84.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	debug = true
	
[[plugins]]
package = "./plugins/image-optim"

[[plugins]]
package = "@netlify/plugin-local-install-core"